version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    entrypoint: ["sh", "-c", "mysqld --init-file=/docker-entrypoint-initdb.d/data.sql"]
    
  spring-boot-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bees_api_d
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql